/*2 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
#include<iostream>
void fibonacci();
using namespace std;
int main()
{
	long int aux=1, post, suma=1, res=0;
	cout<<"la posicion del numero fibonacci : "; cin>>post;
	for(int i=1; i<=post; i++) 
	{	
		aux=aux+suma;
		suma=aux-suma;
		if(suma<4000000 && suma%2==0)	
		{
			cout<<suma<<endl;
			res=res+suma;
		}
	}
		cout<<res;  //0 1 1 2 3 5 8 13 21 34+20 
	return 0;
}
